name: Reusable MkDocs Publish Workflow

on:
  workflow_call:
    inputs:
      source-repo:
        description: 'Source repository (org/repo format)'
        required: true
        type: string
      pages-repo:
        description: 'Target Pages repository'
        required: true
        type: string
      publish-path:
        description: 'Path in pages repo to publish to'
        required: true
        type: string
      pages-branch:
        description: 'Branch of pages repo'
        required: false
        type: string
        default: 'master'
      runner-labels:
        description: 'JSON array of runner labels'
        required: false
        type: string
        default: '["self-hosted", "arc-runner", "cpu-only"]'
      container-image:
        description: 'Container image to use for the job'
        required: false
        type: string
        default: 'python:3.11-slim-bookworm'
    secrets:
      docs-deploy-token:
        description: 'PAT for pushing to pages repo'
        required: true

jobs:
  build-and-deploy:
    if: ${{ github.repository == inputs.source-repo }}
    runs-on: ${{ fromJson(inputs.runner-labels) }}
    container:
      image: ${{ inputs.container-image }}
      options: --user root  # Needed for git operations
    permissions:
      contents: read
    env:
      PUBLISH_PATH: ${{ inputs.publish-path }}
    steps:
      # Install required tools in container
      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y git rsync openssh-client ca-certificates curl

      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Install MkDocs + plugins
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
    
      - name: Build site
        run: mkdocs build --strict --site-dir site

      - name: Upload built site (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
          if-no-files-found: error
          retention-days: 7

      - name: Checkout Pages repo (production)
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.pages-repo }}
          ref: ${{ inputs.pages-branch }}
          token: ${{ secrets.docs-deploy-token }}
          path: pages

      - name: Sync built site into /${{ env.PUBLISH_PATH }}
        run: |
          set -euo pipefail
          mkdir -p "pages/${{ env.PUBLISH_PATH }}"
          rsync -a --delete site/ "pages/${{ env.PUBLISH_PATH }}/"

      - name: Commit & push to pages repo
        run: |
          set -euo pipefail
          cd pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Publish docs from ${GITHUB_REPOSITORY}@${GITHUB_SHA}"
            git push origin ${{ inputs.pages-branch }}
          else
            echo "No changes to publish."
          fi
