name: Reusable Dockerless Build and Push

on:
  push:
    branches: [ new-yasp-compile ]
    tags: [ '*' ]
  pull_request:
    branches: [ new-yasp-compile ]
    types: [ opened, synchronize, reopened, ready_for_review ]

env:
  REGISTRY: registry.yasp.localdomain:5050
  IMAGE_NAME: yasp-compile
  STORAGE_DRIVER: overlay
  BUILDAH_ISOLATION: chroot
  DOCKERFILE: Dockerfile
  BUILD_TARGET: ci

jobs:
  build-and-push:
    runs-on: gpu-runners
    container:
      image: quay.io/buildah/stable:latest
      options: >-
        --user 0
        --privileged
        --security-opt seccomp=unconfined
        --security-opt apparmor=unconfined
        --device /dev/fuse
        --cap-add SYS_ADMIN
        --cap-add SYS_CHROOT
        --cap-add SETUID
        --cap-add SETGID
    
    steps:
      - name: Checkout calling repository
        uses: actions/checkout@v5
      
      - name: DEBUG - Check if checkout worked
        run: |
          echo "==== DEBUG: After First Checkout ===="
          echo "Current directory: $(pwd)"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo ""
          echo "Contents of current directory:"
          ls -la || echo "ls failed!"
          echo ""
          echo "Does Dockerfile exist here?"
          [ -f Dockerfile ] && echo "YES - Dockerfile found!" || echo "NO - Dockerfile NOT found!"
          echo ""
          echo "Contents of /:"
          ls -la / 2>/dev/null || echo "Can't list /"
          echo ""
          echo "Contents of /__w:"
          ls -la /__w 2>/dev/null || echo "/__w doesn't exist"
          echo ""
          echo "Contents of /__w/.github:"
          ls -la /__w/.github 2>/dev/null || echo "/__w/.github doesn't exist"
          echo ""
          echo "Contents of /__w/.github/.github:"
          ls -la /__w/.github/.github 2>/dev/null || echo "/__w/.github/.github doesn't exist"
      
      - name: Checkout .github repo for scripts
        uses: actions/checkout@v5
        with:
          repository: Naio-SWE/.github
          path: .github-repo
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: DEBUG - Check after second checkout
        run: |
          echo "==== DEBUG: After Second Checkout ===="
          echo "Current directory: $(pwd)"
          ls -la
          echo ""
          echo ".github-repo exists?"
          [ -d .github-repo ] && echo "YES" || echo "NO"
          echo ""
          echo "Contents of .github-repo/scripts:"
          ls -la .github-repo/scripts 2>/dev/null || echo ".github-repo/scripts doesn't exist"
      
      - name: Show environment info
        run: ./.github-repo/scripts/dockerless-build-action/show-env.sh
      
      - name: Configure Buildah storage
        run: ./.github-repo/scripts/dockerless-build-action/configure-storage.sh
      
      - name: Login to registry
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: ./.github-repo/scripts/dockerless-build-action/registry-login.sh
      
      - name: DEBUG - Right before build
        run: |
          echo "==== DEBUG: Right Before Build ===="
          echo "Current directory: $(pwd)"
          ls -la
          echo ""
          echo "Searching for Dockerfile:"
          find . -name "Dockerfile*" -type f 2>/dev/null || echo "No Dockerfile found"
          echo ""
          echo "First 20 files in workspace:"
          find . -type f 2>/dev/null | head -20
      
      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: ./.github-repo/scripts/dockerless-build-action/build-image.sh
      
      - name: Push image to registry
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: ./.github-repo/scripts/dockerless-build-action/push-image.sh
      
      - name: Verify image
        run: ./.github-repo/scripts/dockerless-build-action/verify-image.sh
      
      - name: Cleanup
        if: always()
        run: ./.github-repo/scripts/dockerless-build-action/cleanup.sh
